# In compatibility to builtin FindLAPACK.cmake before v3.5.4
if(DEFINED LAPACK_DIR)
  string(APPEND CMAKE_PREFIX_PATH ";${LAPACK_DIR}")
endif()
if(DEFINED LAPACK_LIBRARY)
  set(LAPACK_LIBRARIES ${LAPACK_LIBRARY})
endif()

find_package(Blas REQUIRED)
find_package(LAPACK REQUIRED)

# find LAPACKE libraries
find_library(LAPACKE_LIBRARY
  NAMES lapacke
  PATHS ${LAPACK_DIR} ${LAPACK_LIBRARIES} ${CMAKE_PREFIX_PATH}
  PATH_SUFFIXES lib lib64
  DOC "Path to LAPACKE library"
)

if(NOT TARGET LAPACK::LAPACK)
    add_library(LAPACK::LAPACK UNKNOWN IMPORTED)
    set_target_properties(LAPACK::LAPACK PROPERTIES
        IMPORTED_LINK_INTERFACE_LANGUAGES "C"
        IMPORTED_LOCATION "${LAPACK_LIBRARIES}")
endif()

if(NOT TARGET LAPACKE::LAPACKE)
  add_library(LAPACKE::LAPACKE UNKNOWN IMPORTED)
  set_target_properties(LAPACKE::LAPACKE PROPERTIES
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
    IMPORTED_LOCATION "${LAPACKE_LIBRARY}")

  set_target_properties(LAPACKE::LAPACKE PROPERTIES
    INTERFACE_LINK_LIBRARIES "LAPACK::LAPACK"
  )
endif()
